package dlt.dltbackendmaster.dto;
// Generated Jun 13, 2022, 9:37:47 AM by Hibernate Tools 5.2.12.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;

import dlt.dltbackendmaster.domain.District;
import dlt.dltbackendmaster.domain.Locality;
import dlt.dltbackendmaster.domain.Partners;
import dlt.dltbackendmaster.domain.Profiles;
import dlt.dltbackendmaster.domain.Province;
import dlt.dltbackendmaster.domain.References;
import dlt.dltbackendmaster.domain.Us;
import dlt.dltbackendmaster.domain.Users;

/**
 * Users generated by hbm2java
 */

public class UsersDTO implements java.io.Serializable {

	private static final long serialVersionUID = 8573980496179099357L;

	private Integer id;

	private Partners partners;

	private Profiles profiles;

	private String surname;

	private String name;

	private String phoneNumber;

	private String phoneNumber2;

	private String email;

	private String username;

	private String entryPoint;

	private int status;

	private Byte isLocked;

	private Byte isExpired;

	private Byte isCredentialsExpired;

	private Byte isEnabled;

	private int createdBy;

	private Date dateCreated;

	private Integer updatedBy;

	private Date dateUpdated;

	private String offlineId;

	private Integer newPassword;

	private String recoverPassword;

	private String recoverPasswordToken;

	private Date passwordLastChangeDate;

	private Set<Locality> localities = new HashSet<Locality>(0);

	private Set<District> districts = new HashSet<District>(0);

	private Set<Province> provinces = new HashSet<Province>(0);

	private Set<Us> us = new HashSet<Us>(0);

	private Set<References> referenceses = new HashSet<References>(0);

	private String recoverPasswordOrigin;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Partners getPartners() {
		return this.partners;
	}

	public void setPartners(Partners partners) {
		this.partners = partners;
	}

	public Profiles getProfiles() {
		return this.profiles;
	}

	public void setProfiles(Profiles profiles) {
		this.profiles = profiles;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getPhoneNumber2() {
		return this.phoneNumber2;
	}

	public void setPhoneNumber2(String phoneNumber2) {
		this.phoneNumber2 = phoneNumber2;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEntryPoint() {
		return this.entryPoint;
	}

	public void setEntryPoint(String entryPoint) {
		this.entryPoint = entryPoint;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "is_locked")
	public Byte getIsLocked() {
		return this.isLocked;
	}

	public void setIsLocked(Byte isLocked) {
		this.isLocked = isLocked;
	}

	@Column(name = "is_expired")
	public Byte getIsExpired() {
		return this.isExpired;
	}

	public void setIsExpired(Byte isExpired) {
		this.isExpired = isExpired;
	}

	@Column(name = "is_credentials_expired")
	public Byte getIsCredentialsExpired() {
		return this.isCredentialsExpired;
	}

	public void setIsCredentialsExpired(Byte isCredentialsExpired) {
		this.isCredentialsExpired = isCredentialsExpired;
	}

	@Column(name = "is_enabled")
	public Byte getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Byte isEnabled) {
		this.isEnabled = isEnabled;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public String getOfflineId() {
		return this.offlineId;
	}

	public void setOfflineId(String offlineId) {
		this.offlineId = offlineId;
	}

	public Integer getNewPassword() {
		return this.newPassword;
	}

	public void setNewPassword(Integer newPassword) {
		this.newPassword = newPassword;
	}

	public String getRecoverPassword() {
		return this.recoverPassword;
	}

	public void setRecoverPassword(String recoverPassword) {
		this.recoverPassword = recoverPassword;
	}

	public String getRecoverPasswordToken() {
		return recoverPasswordToken;
	}

	public void setRecoverPasswordToken(String recoverPasswordToken) {
		this.recoverPasswordToken = recoverPasswordToken;
	}

	public Set<Locality> getLocalities() {
		return this.localities;
	}

	public void setLocalities(Set<Locality> localities) {
		this.localities = localities;
	}

	public Set<District> getDistricts() {
		return this.districts;
	}

	public void setDistricts(Set<District> districts) {
		this.districts = districts;
	}

	public Set<Province> getProvinces() {
		return this.provinces;
	}

	public void setProvinces(Set<Province> provinces) {
		this.provinces = provinces;
	}

	public Set<Us> getUs() {
		return this.us;
	}

	public void setUs(Set<Us> us) {
		this.us = us;
	}

	public Set<References> getReferenceses() {
		return this.referenceses;
	}

	public void setReferenceses(Set<References> referenceses) {
		this.referenceses = referenceses;
	}

	public Date getPasswordLastChangeDate() {
		return passwordLastChangeDate;
	}

	public void setPasswordLastChangeDate(Date passwordLastChangeDate) {
		this.passwordLastChangeDate = passwordLastChangeDate;
	}

	public String getRecoverPasswordOrigin() {
		return recoverPasswordOrigin;
	}

	public void setRecoverPasswordOrigin(String recoverPasswordOrigin) {
		this.recoverPasswordOrigin = recoverPasswordOrigin;
	}

	public UsersDTO transformToDTO(Users user) {
		UsersDTO userDTO = new UsersDTO();

		userDTO.setDateCreated(user.getDateCreated());
		userDTO.setProfiles(user.getProfiles());
		userDTO.setId(user.getId());
		userDTO.setPartners(user.getPartners());
		userDTO.setProfiles(user.getProfiles());
		userDTO.setSurname(user.getSurname());
		userDTO.setName(user.getName());
		userDTO.setPhoneNumber(user.getPhoneNumber());
		userDTO.setPhoneNumber2(user.getPhoneNumber2());
		userDTO.setEmail(user.getEmail());
		userDTO.setUsername(user.getUsername());
		userDTO.setEntryPoint(user.getEntryPoint());
		userDTO.setStatus(user.getStatus());
		userDTO.setIsLocked(user.getIsLocked());
		userDTO.setIsExpired(user.getIsExpired());
		userDTO.setIsCredentialsExpired(user.getIsCredentialsExpired());
		userDTO.setIsEnabled(user.getIsEnabled());
		userDTO.setCreatedBy(user.getCreatedBy());
		userDTO.setDateCreated(user.getDateCreated());
		userDTO.setUpdatedBy(user.getUpdatedBy());
		userDTO.setDateUpdated(user.getDateUpdated());
		userDTO.setOfflineId(user.getOfflineId());
		userDTO.setNewPassword(user.getNewPassword());
		userDTO.setRecoverPassword(user.getRecoverPassword());
		userDTO.setRecoverPasswordToken(user.getRecoverPasswordToken());
		userDTO.setPasswordLastChangeDate(user.getPasswordLastChangeDate());
		userDTO.setLocalities(user.getLocalities());
		userDTO.setDistricts(user.getDistricts());
		userDTO.setProvinces(user.getProvinces());
		userDTO.setUs(user.getUs());
		userDTO.setReferenceses(user.getReferenceses());
		userDTO.setRecoverPasswordOrigin(user.getRecoverPasswordOrigin());

		return userDTO;
	}

	public List<UsersDTO> transformToDTOS(List<Users> users) {

		List<UsersDTO> usersDTOS = new ArrayList<>();

		for (Users user : users) {
			UsersDTO userDTO = transformToDTO(user);
			usersDTOS.add(userDTO);
		}
		return usersDTOS;
	}
}
